spring:
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
#        format_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/ntt;MODE=MYSQL
    #url: jdbc:h2:mem:ntt;MODE=MYSQL
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  config:
    import:
      - classpath:/DevChat-secret/application-secret.yml